# Generated by Django 6.0.4 on 2026-05-04 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_processo', models.CharField(max_length=32, verbose_name='número do processo')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='data de entrada')),
                ('apensos', models.CharField(blank=True, max_length=120, verbose_name='apensos')),
                ('data_distribuicao', models.DateField(blank=True, null=True, verbose_name='data de distribuição')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('situacao', models.CharField(choices=[('entregue', 'Entregue'), ('andamento', 'Em andamento'), ('caderno', 'Entregue no caderno'), ('analise', 'Em análise'), ('concluido', 'Concluído')], default='andamento', max_length=20, verbose_name='situação')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('importado', models.BooleanField(default=False, verbose_name='importado da planilha')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_geral', to='core.assunto', verbose_name='assunto')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_geral_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('destino_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_geral', to='core.setor', verbose_name='destino da saída')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_geral', to='core.procurador', verbose_name='responsável')),
                ('responsavel_secundario', models.ForeignKey(blank=True, help_text='Usado quando o processo é dividido entre dois procuradores.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_geral_secundario', to='core.procurador', verbose_name='co-responsável')),
                ('tipos_parecer', models.ManyToManyField(blank=True, related_name='processos_geral', to='core.tipoparecer', verbose_name='tipos de parecer')),
            ],
            options={
                'verbose_name': 'processo (geral)',
                'verbose_name_plural': 'processos (geral)',
                'ordering': ['-ano', '-data_entrada', '-criado_em'],
                'indexes': [models.Index(fields=['ano'], name='geral_proce_ano_de4341_idx'), models.Index(fields=['situacao'], name='geral_proce_situaca_526b04_idx'), models.Index(fields=['responsavel'], name='geral_proce_respons_de85fc_idx'), models.Index(fields=['destino_saida'], name='geral_proce_destino_c0ca75_idx')],
                'unique_together': {('numero_processo', 'ano')},
            },
        ),
    ]
