# Generated by Django 6.0.4 on 2026-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processogeral',
            name='situacao',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('andamento', 'Em andamento'), ('caderno', 'Entregue no caderno'), ('analise', 'Em análise'), ('concluido', 'Concluído'), ('distribuicao', 'Distribuição')], default='andamento', max_length=20, verbose_name='situação'),
        ),
    ]
