# Generated by Django 6.0.4 on 2026-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_alter_processogeral_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processogeral',
            name='situacao',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('andamento', 'Em andamento'), ('caderno', 'Entregue no caderno'), ('analise', 'Em análise'), ('concluido', 'Concluído'), ('distribuicao', 'Distribuição'), ('arquivado', 'Arquivado')], default='andamento', max_length=20, verbose_name='situação'),
        ),
    ]
