# Generated by Django 6.0.4 on 2026-05-04 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão')], max_length=16, verbose_name='ação')),
                ('actor_username', models.CharField(blank=True, help_text='Username preservado mesmo quando o usuário é excluído ou anônimo.', max_length=150, verbose_name='usuário (snapshot)')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID do objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='representação do objeto')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='antes')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='depois')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='campos alterados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='contenttypes.contenttype', verbose_name='tipo do objeto')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_2f8c97_idx'), models.Index(fields=['actor'], name='auditoria_a_actor_i_3ba417_idx'), models.Index(fields=['action'], name='auditoria_a_action_1263d1_idx'), models.Index(fields=['-timestamp'], name='auditoria_a_timesta_f4f9be_idx')],
            },
        ),
    ]
