# Generated by Django 6.0.4 on 2026-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('modulo', models.CharField(choices=[('fazendaria', 'Fazendária'), ('geral', 'Geral'), ('ambos', 'Ambos')], default='ambos', max_length=16, verbose_name='módulo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'procurador',
                'verbose_name_plural': 'procuradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('sigla', models.CharField(blank=True, max_length=32, verbose_name='sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoParecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tipo de parecer',
                'verbose_name_plural': 'tipos de parecer',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('modulo', models.CharField(choices=[('fazendaria', 'Fazendária'), ('geral', 'Geral'), ('ambos', 'Ambos')], default='ambos', max_length=16, verbose_name='módulo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'assunto',
                'verbose_name_plural': 'assuntos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'modulo')},
            },
        ),
    ]
