# Generated by Django 6.0.4 on 2026-05-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoFazendaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_processo', models.CharField(max_length=32, verbose_name='número do processo')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='data de recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('situacao', models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('remessa', 'Remessa'), ('no_armario', 'No armário')], default='andamento', max_length=20, verbose_name='situação')),
                ('data_remessa', models.DateField(blank=True, null=True, verbose_name='data da remessa')),
                ('importado', models.BooleanField(default=False, verbose_name='importado da planilha')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_fazendaria', to='core.assunto', verbose_name='assunto')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_fazendaria_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_fazendaria', to='core.setor', verbose_name='destino')),
                ('procurador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_fazendaria', to='core.procurador', verbose_name='procurador')),
                ('tipos_parecer', models.ManyToManyField(blank=True, related_name='processos_fazendaria', to='core.tipoparecer', verbose_name='tipos de parecer')),
            ],
            options={
                'verbose_name': 'processo (fazendária)',
                'verbose_name_plural': 'processos (fazendária)',
                'ordering': ['-ano', '-data_recebimento', '-criado_em'],
                'indexes': [models.Index(fields=['ano'], name='fazendaria__ano_36d1f5_idx'), models.Index(fields=['situacao'], name='fazendaria__situaca_d8e846_idx'), models.Index(fields=['procurador'], name='fazendaria__procura_cb4c40_idx'), models.Index(fields=['destino'], name='fazendaria__destino_9d0492_idx')],
                'unique_together': {('numero_processo', 'ano')},
            },
        ),
    ]
