# Generated by Django 6.0.4 on 2026-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processofazendaria',
            name='situacao',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('remessa', 'Remessa'), ('no_armario', 'No armário'), ('distribuicao', 'Distribuição')], default='andamento', max_length=20, verbose_name='situação'),
        ),
    ]
