# Generated by Django 6.0.4 on 2026-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendaria', '0003_alter_processofazendaria_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processofazendaria',
            name='situacao',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('remessa', 'Remessa'), ('no_armario', 'No armário'), ('distribuicao', 'Distribuição'), ('arquivado', 'Arquivado'), ('entregue', 'Entregue'), ('diario_oficial', 'Diário Oficial')], default='andamento', max_length=20, verbose_name='situação'),
        ),
    ]
