# Generated by Django 6.0.4 on 2026-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendaria', '0004_alter_processofazendaria_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processofazendaria',
            name='data_distribuicao',
            field=models.DateField(blank=True, null=True, verbose_name='data de distribuição'),
        ),
    ]
